
#定义外部上传路径
web:
 upload-path: /Users/user12/Desktop/upload/




spring:
  redis:
  database: 1
  host: localhost
  pool:
    max-active: 20
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/forum
    username: root
    password: xihanzhiwen
  http:
    multipart:
      maxFileSize: 100Mb
      maxRequestSize: 100Mb


  thymeleaf:
        enabled: true
        prefix: classpath:/templates/
        suffix: .html
        content-type: text/html
        encoding: UTF-8
        check-template-location: false
        check-template: false
        mode: HTML5
        cache: false

#logging:
 # pattern:
  #  console: "%d - %msg%n"
  #path: /Users/user12/documents/test
  #file: /Users/user12/documents/test/test1.log
  #level:
   #  com.nchu.controller.logTest: debug
  #level: debug

mybatis:
  config-location: classpath:mybatis-config.xml
 # type-aliases-package: com.nchu.domain.DO
  #mapper-locations: classpath:mybatis-mapper/*.xml


logging:
  level:
    org:
     hibernate: debug